### ISSUE TITLE
Please approve the PR of jaredfholgate and take your Charles Zip heritage seriously.

### ISSUE THREAD

**Issue by momeijer** [jason-johnson/azure-pipelines-tasks-terraform#358]

**Comment by jason-johnson** [comment]
@momeijer  We are in conversation with Jared and I've added him to the organisation.  I have not approved the change because we cannot test it currently.  We are in the middle of trying to support versioning in the extension so we can have a more modern release cycle than is possible with the current setup but until that is done releases are broken in most of the environments.
