### ISSUE TITLE
Add `-backend-config="access_key=..."` as GUI option

### ISSUE THREAD

**Issue by vladkasianenko** [jason-johnson/azure-pipelines-tasks-terraform#55]
Hello. There's a plenty of setup for Azure Backend, but there's no option for "Access Key", which would be great.

**Comment by charleszipp** [comment]
@vladkasianenko if using a service connection (whose configured SPN has access to storage account) you should not need to provide an access key. This is why there is no option to provide an access key. This is typically preferred because it reduces the amount of secrets to manage; which also makes it a more secure option. Could you elaborate why a service connection/principal could not be used?

**Comment by charleszipp** [comment]
Additionally, if you must use an access key, the [self-configured option](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/main/overview.md#secure-env-files) combined with a [secure env file](https://github.com/charleszipp/azure-pipelines-tasks-terraform/blob/main/overview.md#secure-env-files) would allow you to do this.

**Comment by charleszipp** [comment]
Closing this as there are other options to provide the access key for azurerm as well as password/secrets for other types of backends.
