### ISSUE TITLE
Microsoft upstream?

### ISSUE THREAD

**Issue by PaulusTM** [jason-johnson/azure-pipelines-tasks-terraform#63]
How is this repo different from the microsoft/azure-pipelines-extensions version of the TF extension?

Can't seem to find any docs on this.

Thank you!

**Comment by charleszipp** [comment]
The one from the microsoft repo you mention is an entirely different extension that was created after this one. This one originated in Nov 2018 before the microsoft one was available and was developed as a personal project not as an official microsoft supported extension (i.e. there is no dev team within microsoft dedicated to supporting it). Due to having to recreate the repo earlier this year, it may appear newer than it actually is. However, the dates on the marketplace pages reflect the age appropriately.

If you are looking for differences in features, I would checkout the marketplace pages for each.
microsoft/azure-pipelines-extensions -> [ms-devlabs.custom-terraform-tasks](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks)
charleszipp/azure-pipelines-tasks-terraform -> [charleszipp.azure-pipelines-tasks-terraform](https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform)

**Comment by PaulusTM** [comment]
Thank you for the quick reply and the effort you put in this extension :)
